# Generated by Django 3.0.2 on 2020-01-08 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('availability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skedge.Availability')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skedge.Schedule')),
            ],
        ),
    ]
