# Generated by Django 3.0.2 on 2020-01-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skedge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
