# Generated by Django 3.0.2 on 2020-01-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skedge', '0002_auto_20200110_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='w0_0',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w0_1',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w0_2',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w0_3',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w1_0',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w1_1',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w1_2',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w1_3',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w2_0',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w2_1',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w2_2',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w2_3',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w3_0',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w3_1',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w3_2',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w3_3',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w4_0',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w4_1',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w4_2',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='w4_3',
            field=models.CharField(choices=[('N', 'Not working'), ('W', 'Working')], default='N', max_length=1),
        ),
    ]
