# Generated by Django 3.0.2 on 2020-01-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skedge', '0003_auto_20200110_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='a0_0',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a0_1',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a0_2',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a0_3',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a1_0',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a1_1',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a1_2',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a1_3',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a2_0',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a2_1',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a2_2',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a2_3',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a3_0',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a3_1',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a3_2',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a3_3',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a4_0',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a4_1',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a4_2',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='availability',
            name='a4_3',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available'), ('W', 'Working')], default='N', max_length=1),
        ),
    ]
