# Generated by Django 3.0.2 on 2020-01-10 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skedge', '0004_auto_20200110_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='schedule',
        ),
        migrations.AddField(
            model_name='availability',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='skedge.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='skedge.Employee'),
            preserve_default=False,
        ),
    ]
