# Generated by Django 3.0.2 on 2020-01-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skedge', '0005_auto_20200110_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p0_0', models.IntegerField()),
                ('p0_1', models.IntegerField()),
                ('p0_2', models.IntegerField()),
                ('p0_3', models.IntegerField()),
                ('p1_0', models.IntegerField()),
                ('p1_1', models.IntegerField()),
                ('p1_2', models.IntegerField()),
                ('p1_3', models.IntegerField()),
                ('p2_0', models.IntegerField()),
                ('p2_1', models.IntegerField()),
                ('p2_2', models.IntegerField()),
                ('p2_3', models.IntegerField()),
                ('p3_0', models.IntegerField()),
                ('p3_1', models.IntegerField()),
                ('p3_2', models.IntegerField()),
                ('p3_3', models.IntegerField()),
                ('p4_0', models.IntegerField()),
                ('p4_1', models.IntegerField()),
                ('p4_2', models.IntegerField()),
                ('p4_3', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='weekly_ideal',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
