# Generated by Django 3.0.2 on 2020-01-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skedge', '0006_auto_20200115_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='weekly_ideal',
            field=models.IntegerField(default=0),
        ),
    ]
